name: writer-002
cluster-name: cluster-test
cluster-role: writer
cluster-client-url: http://127.0.0.1:22379
cluster-peer-url: http://127.0.0.1:22380
cluster-join-urls: http://127.0.0.1:12380
api-addr: 127.0.0.1:22381
data-dir: ./data
wal-dir: ""
cpu-profile-file:
memory-profile-file:
log-dir: ./log
member-dir: ./member
std-log-level: INFO
